
const $=id=>document.getElementById(id), sb=supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);let USER=null,S={profile:null,items:[],vials:[],progress:[],daily:[],workouts:[]};
const prof={name:'Roly',plan_title:'Transformation 2026',age:54,height:"5'9",units:'imperial',start_date:new Date().toISOString().slice(0,10),starting_weight:187,goal_weight:150,current_weight:187,protein_goal:170,water_goal:4,sleep_goal:7.5,vial_limit_days:30,meal_template:'Breakfast: eggs, oats, berries\nSnack: Greek yogurt, almonds\nLunch: chicken, rice, vegetables\nDinner: lean protein, vegetables'};
const defs=[['Retatrutide','Weight management',true,['Sunday'],'red',2,'mg','SubQ','Anytime'],['KLOW','Recovery / tissue support',true,['Monday','Tuesday','Wednesday','Thursday','Friday'],'green',2,'mg','SubQ','Anytime'],['Tesamorelin','Body composition',true,['Monday','Tuesday','Wednesday','Thursday','Friday'],'blue',0,'mg','SubQ','Night'],['Ipamorelin','Recovery / sleep routine',true,['Monday','Tuesday','Wednesday','Thursday','Friday'],'blue',0,'mcg','SubQ','Night'],['MOTS-c','Metabolic support',true,['Monday','Thursday'],'orange',0,'mg','SubQ','Morning'],['Kisspeptin','Hormonal support',false,[],'yellow',0,'mcg','SubQ','Anytime']];
const W={Sunday:'Rest',Monday:'Chest + Triceps',Tuesday:'Back + Biceps',Wednesday:'Cardio + Abs',Thursday:'Legs',Friday:'Shoulders modified + Abs',Saturday:'Light cardio / mobility'};function iso(d){return d.toISOString().slice(0,10)}function dow(d=new Date()){return d.toLocaleDateString('en-US',{weekday:'long'})}function msg(t){$('status').textContent=t}function amsg(t){$('authMsg').textContent=t}
$('tabLogin').onclick=()=>{$('loginBox').classList.remove('hide');$('signupBox').classList.add('hide');$('tabLogin').classList.add('active');$('tabSignup').classList.remove('active')};$('tabSignup').onclick=()=>{$('signupBox').classList.remove('hide');$('loginBox').classList.add('hide');$('tabSignup').classList.add('active');$('tabLogin').classList.remove('active')};
$('signupBtn').onclick=async()=>{let email=$('signupEmail').value.trim(),password=$('signupPass').value,name=$('signupName').value.trim();if(!email||!password)return amsg('Enter email and password.');amsg('Creating account...');let {data,error}=await sb.auth.signUp({email,password,options:{data:{name}}});if(error)return amsg(error.message);if(data.session){USER=data.user;start()}else amsg('Account created. Check your email if confirmation is ON, then login.')};
$('loginBtn').onclick=async()=>{let email=$('loginEmail').value.trim(),password=$('loginPass').value;if(!email||!password)return amsg('Enter email and password.');let {data,error}=await sb.auth.signInWithPassword({email,password});if(error)return amsg(error.message);USER=data.user;start()};$('logout').onclick=async()=>{await sb.auth.signOut();location.reload()};
async function boot(){let {data}=await sb.auth.getSession();if(data.session?.user){USER=data.session.user;start()}else{$('auth').classList.remove('hide');$('app').classList.add('hide')}}async function start(){$('auth').classList.add('hide');$('app').classList.remove('hide');$('email').textContent=USER.email||'';await init()}
async function init(){try{msg('Loading private cloud data...');let {data:p,error}=await sb.from('user_profiles').select('*').eq('user_id',USER.id).limit(1);if(error)throw error;if(!p?.length){let name=USER.user_metadata?.name||(USER.email||'').split('@')[0];let r=await sb.from('user_profiles').insert({...prof,name,user_id:USER.id}).select().single();if(r.error)throw r.error;S.profile=r.data}else S.profile=p[0];let it=await sb.from('peptide_items').select('*').eq('user_id',USER.id);if(it.error)throw it.error;if(!it.data?.length){for(const x of defs)await sb.from('peptide_items').insert({user_id:USER.id,name:x[0],purpose:x[1],active:x[2],schedule_days:x[3],color:x[4],dose_amount:x[5],dose_unit:x[6],route:x[7],time_of_day:x[8]})}await load();msg('Cloud connected • private account')}catch(e){msg('Cloud error: '+e.message);console.error(e)}}
async function load(){let [items,vials,progress,daily,workouts]=await Promise.all([sb.from('peptide_items').select('*').eq('user_id',USER.id).order('created_at'),sb.from('vial_inventory').select('*').eq('user_id',USER.id).order('created_at',{ascending:false}),sb.from('progress_logs').select('*').eq('user_id',USER.id).order('log_date',{ascending:false}),sb.from('daily_logs').select('*').eq('user_id',USER.id).order('log_date',{ascending:false}),sb.from('workout_plan').select('*').eq('user_id',USER.id)]);S.items=items.data||[];S.vials=vials.data||[];S.progress=progress.data||[];S.daily=daily.data||[];S.workouts=workouts.data||[];render()}
function workout(day){return S.workouts.find(x=>x.day_name===day)?.workout_name||W[day]}function tasks(day){return S.items.filter(x=>x.active&&(x.schedule_days||[]).includes(day))}function logs(date){return S.daily.filter(x=>x.log_date===date)}function logFor(date,name){return S.daily.find(x=>x.log_date===date&&x.item_name===name)}function pill(t){return `<span class=pill>${t}</span>`}
function render(){home();profile();items();vials();progress();daily();gym();food();calc();chart()}function home(){let p=S.profile||prof,start=+p.starting_weight,goal=+p.goal_weight,cur=+p.current_weight,total=Math.abs(start-goal)||1,pct=Math.min(100,Math.max(0,Math.round(Math.abs(start-cur)/total*100)));$('title').textContent=`${p.name||'My'} ${p.plan_title||'Tracker'}`;$('startW').textContent=start;$('goalW').textContent=goal;$('curW').textContent=cur;$('remainW').textContent=Math.abs(cur-goal).toFixed(1);$('pct').textContent=pct+'%';document.querySelector('.ring').style.setProperty('--deg',(pct*3.6)+'deg');document.querySelectorAll('.wu').forEach(x=>x.textContent=p.units==='metric'?'kg':'lb');$('unitW').textContent=p.units==='metric'?'kg':'lb';$('goalText').textContent=`Protein ${p.protein_goal}g • Water ${p.water_goal}L • Sleep ${p.sleep_goal}h`;$('activeCount').textContent=S.items.filter(x=>x.active).length;let d=iso(new Date()),ts=tasks(dow()),ls=logs(d);$('todayCount').textContent=`${ls.filter(x=>x.status==='Done').length}/${ts.length}`;$('todayList').innerHTML='';ts.forEach(i=>$('todayList').appendChild(row(d,i,true)))}
function row(date,item,compact){let l=logFor(date,item.name)||{},div=document.createElement('div');div.className='row '+(l.status==='Done'?'done':'');let dose=l.dose_amount??item.dose_amount??'',unit=l.dose_unit||item.dose_unit||'mg';div.innerHTML=`<div class=rowtop><div><b>${item.name}</b><p class="muted small">Suggested: ${item.dose_amount||'-'} ${item.dose_unit||''} • ${item.route||''} • ${item.time_of_day||''}</p></div><button class=smallbtn>${l.status==='Done'?'✓ Done':'Mark'}</button></div>${compact?'':`<div class=dailygrid><label>Dose taken<input class=dose type=number step=.001 value="${dose}"></label><label>Unit<select class=unit><option ${unit==='mg'?'selected':''}>mg</option><option ${unit==='mcg'?'selected':''}>mcg</option><option ${unit==='units'?'selected':''}>units</option><option ${unit==='mL'?'selected':''}>mL</option><option ${unit==='N/A'?'selected':''}>N/A</option></select></label><label>Notes<input class=note value="${l.notes||''}"></label></div><button class="smallbtn saveDose">Save dose/progress</button>`}`;div.querySelector('.rowtop button').onclick=async()=>{await saveDaily(date,item,{status:l.status==='Done'?'Pending':'Done',dose_amount:dose||null,dose_unit:unit});await load()};let b=div.querySelector('.saveDose');if(b)b.onclick=async()=>{await saveDaily(date,item,{status:'Done',dose_amount:+div.querySelector('.dose').value||null,dose_unit:div.querySelector('.unit').value,notes:div.querySelector('.note').value});await load()};return div}
async function saveDaily(date,item,payload){let l=logFor(date,item.name),row={user_id:USER.id,log_date:date,item_name:item.name,...payload};if(l)await sb.from('daily_logs').update(row).eq('id',l.id).eq('user_id',USER.id);else await sb.from('daily_logs').insert(row)}
function daily(){let box=$('days');box.innerHTML='';let p=S.profile||prof,start=new Date((p.start_date||iso(new Date()))+'T00:00:00');for(let i=0;i<90;i++){let d=new Date(start);d.setDate(start.getDate()+i);let date=iso(d),day=dow(d),ts=tasks(day),m=metricsFor(date)||{},doneCount=ts.filter(t=>logFor(date,t.name)?.status==='Done').length,div=document.createElement('div');div.className='card';div.innerHTML=`<p class=eyebrow>Day ${i+1} • ${date} • ${day}</p><h3>${doneCount}/${ts.length} done</h3><div class=dailygrid><label>Weight<input data-m=weight type=number step=.1 value="${m.weight||''}"></label><label>Waist<input data-m=waist type=number step=.1 value="${m.waist||''}"></label><label>Sleep<input data-m=sleep_hours type=number step=.1 value="${m.sleep_hours||''}"></label><label>Water L<input data-m=water_l type=number step=.1 value="${m.water_l||''}"></label><label>Protein g<input data-m=protein_g type=number value="${m.protein_g||''}"></label><label>Energy<input data-m=mood_energy type=number value="${m.mood_energy||''}"></label><label class=full>Daily notes<input data-m=daily_notes value="${m.daily_notes||''}"></label></div><button class="smallbtn saveMetrics">Save day progress</button><div class=list></div>`;div.querySelector('.saveMetrics').onclick=async()=>{let payload={};div.querySelectorAll('[data-m]').forEach(inp=>payload[inp.dataset.m]=inp.type==='number'?(+inp.value||null):inp.value);await saveMetrics(date,payload);await load()};let list=div.querySelector('.list');if(ts.length)ts.forEach(t=>list.appendChild(row(date,t,false)));else list.innerHTML='<p class=muted>No active peptides/reminders scheduled.</p>';box.appendChild(div)}}
function metricsFor(date){return S.daily.find(x=>x.log_date===date&&x.item_name==='Daily Progress')}
async function saveMetrics(date,payload){let l=metricsFor(date);if(l)await sb.from('daily_logs').update(payload).eq('id',l.id).eq('user_id',USER.id);else await sb.from('daily_logs').insert({user_id:USER.id,log_date:date,item_name:'Daily Progress',status:'Saved',...payload});if(payload.weight)await sb.from('user_profiles').update({current_weight:payload.weight}).eq('id',S.profile.id).eq('user_id',USER.id)}
function profile(){let p=S.profile||prof;[['pName','name'],['pPlan','plan_title'],['pAge','age'],['pHeight','height'],['pUnits','units'],['pStart','start_date'],['pStartW','starting_weight'],['pGoalW','goal_weight'],['pCurW','current_weight'],['pProtein','protein_goal'],['pWater','water_goal'],['pSleep','sleep_goal'],['pVialDays','vial_limit_days']].forEach(([id,k])=>$(id).value=p[k]??'')}
function items(){let box=$('itemList');box.innerHTML='';S.items.forEach(i=>{box.innerHTML+=`<div class=card><h3>${i.name}</h3><p class=muted>${i.purpose||''}</p>${pill((i.active?'Active':'Off'))}${pill((i.dose_amount||'-')+' '+(i.dose_unit||''))}${pill(i.route||'')}${pill(i.time_of_day||'')}<div class="formgrid edit" data-id="${i.id}"><label>Name<input data-f=name value="${i.name||''}"></label><label>Purpose<input data-f=purpose value="${i.purpose||''}"></label><label>Dose<input data-f=dose_amount type=number step=.001 value="${i.dose_amount??''}"></label><label>Unit<input data-f=dose_unit value="${i.dose_unit||''}"></label><label>Route<input data-f=route value="${i.route||''}"></label><label>Time<input data-f=time_of_day value="${i.time_of_day||''}"></label><label>Active<select data-f=active><option value=true ${i.active?'selected':''}>Active</option><option value=false ${!i.active?'selected':''}>Off</option></select></label><label>Color<input data-f=color value="${i.color||'blue'}"></label><label class=full>Days<input data-f=schedule_days value="${(i.schedule_days||[]).join(',')}"></label><label class=full>Dose notes<input data-f=dose_notes value="${i.dose_notes||''}"></label></div><div class=bar><button class=smallbtn onclick="saveItem('${i.id}')">Save changes</button><button class="danger" onclick="del('peptide_items','${i.id}')">Delete</button></div></div>`})}
window.saveItem=async id=>{let w=document.querySelector(`.edit[data-id="${id}"]`),p={};w.querySelectorAll('[data-f]').forEach(el=>{let k=el.dataset.f;if(k==='schedule_days')p[k]=el.value.split(',').map(x=>x.trim()).filter(Boolean);else if(k==='dose_amount')p[k]=+el.value||null;else if(k==='active')p[k]=el.value==='true';else p[k]=el.value});let r=await sb.from('peptide_items').update(p).eq('id',id).eq('user_id',USER.id);if(r.error)alert(r.error.message);await load()}
function vials(){let box=$('vialList');box.innerHTML='';S.vials.forEach(v=>{box.innerHTML+=`<div class=card><h3>${v.quantity||1} × ${v.item_name}</h3><p class=muted>Reconstituted: ${v.reconstituted_date||'-'} • ${v.notes||''}</p><button class=danger onclick="del('vial_inventory','${v.id}')">Delete</button></div>`})}
function progress(){let box=$('progressList');box.innerHTML='';S.progress.forEach(p=>box.innerHTML+=`<div class=card><h3>${p.log_date}</h3><p class=muted>Weight: ${p.weight||'-'} • Waist: ${p.waist||'-'} • Sleep: ${p.sleep_hours||'-'} • Energy: ${p.energy||'-'}</p><button class=danger onclick="del('progress_logs','${p.id}')">Delete</button></div>`)}
function chart(){let cv=$('progressChart');if(!cv)return;let metric=$('chartMetric').value,pts=[...S.progress].filter(p=>p[metric]!=null).sort((a,b)=>a.log_date<b.log_date?-1:1);let ctx=cv.getContext('2d'),w=cv.clientWidth||cv.width,h=cv.height;cv.width=w;ctx.clearRect(0,0,w,h);if(pts.length<2){$('chartEmpty').classList.remove('hide');return}$('chartEmpty').classList.add('hide');let vals=pts.map(p=>+p[metric]),min=Math.min(...vals),max=Math.max(...vals),pad=12,range=(max-min)||1;let x=i=>pad+(i/(pts.length-1))*(w-pad*2),y=v=>h-pad-((v-min)/range)*(h-pad*2);ctx.strokeStyle=getComputedStyle(document.body).getPropertyValue('--blue')||'#38bdf8';ctx.lineWidth=2.5;ctx.beginPath();pts.forEach((p,i)=>{let px=x(i),py=y(+p[metric]);i?ctx.lineTo(px,py):ctx.moveTo(px,py)});ctx.stroke();ctx.fillStyle=ctx.strokeStyle;pts.forEach((p,i)=>{ctx.beginPath();ctx.arc(x(i),y(+p[metric]),3,0,7);ctx.fill()})}
$('chartMetric')?.addEventListener('change',chart);
function gym(){let e=$('workoutEdit'),c=$('workoutCards');e.innerHTML='';c.innerHTML='';['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].forEach(day=>{e.innerHTML+=`<label>${day}<input data-day="${day}" value="${workout(day)}"></label>`;c.innerHTML+=`<div class=card><h3>${day}</h3><p class=muted>${workout(day)}</p></div>`})}
function food(){let p=S.profile||prof;$('foodProtein').textContent=p.protein_goal||'';$('foodWater').textContent=p.water_goal||'';$('foodSleep').textContent=p.sleep_goal||'';$('foodPlan').textContent=p.plan_title||'';$('mealTemplate').value=p.meal_template||prof.meal_template}
window.del=async(t,id)=>{await sb.from(t).delete().eq('id',id).eq('user_id',USER.id);await load()};document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.screen).classList.add('active')});$('theme').onclick=()=>document.body.classList.toggle('light');$('sync').onclick=load;$('refreshDaily').onclick=daily;
$('saveProfile').onclick=async()=>{let p={name:$('pName').value,plan_title:$('pPlan').value,age:+$('pAge').value||null,height:$('pHeight').value,units:$('pUnits').value,start_date:$('pStart').value||null,starting_weight:+$('pStartW').value||null,goal_weight:+$('pGoalW').value||null,current_weight:+$('pCurW').value||null,protein_goal:+$('pProtein').value||null,water_goal:+$('pWater').value||null,sleep_goal:+$('pSleep').value||null,vial_limit_days:+$('pVialDays').value||30};let r=await sb.from('user_profiles').update(p).eq('id',S.profile.id).eq('user_id',USER.id).select().single();if(r.error)return alert(r.error.message);S.profile=r.data;render();alert('Saved')};
$('addItem').onclick=async()=>{let days=$('iDays').value.split(',').map(x=>x.trim()).filter(Boolean);let r=await sb.from('peptide_items').insert({user_id:USER.id,name:$('iName').value,purpose:$('iPurpose').value,dose_amount:+$('iDose').value||null,dose_unit:$('iUnit').value,route:$('iRoute').value,time_of_day:$('iTime').value,active:$('iActive').value==='true',color:$('iColor').value,schedule_days:days,dose_notes:$('iNotes').value});if(r.error)alert(r.error.message);await load()};
$('addVial').onclick=async()=>{let r=await sb.from('vial_inventory').insert({user_id:USER.id,item_name:$('vItem').value,quantity:+$('vQty').value||1,reconstituted_date:$('vDate').value||iso(new Date()),notes:$('vNotes').value});if(r.error)alert(r.error.message);await load()};
$('addProgress').onclick=async()=>{let row={user_id:USER.id,log_date:$('prDate').value||iso(new Date()),weight:+$('prWeight').value||null,waist:+$('prWaist').value||null,sleep_hours:+$('prSleep').value||null,energy:+$('prEnergy').value||null,notes:$('prNotes').value};let r=await sb.from('progress_logs').insert(row);if(r.error)alert(r.error.message);if(row.weight)await sb.from('user_profiles').update({current_weight:row.weight}).eq('id',S.profile.id);await load()};
$('saveWorkout').onclick=async()=>{for(const inp of document.querySelectorAll('[data-day]')){let day=inp.dataset.day,val=inp.value,ex=S.workouts.find(w=>w.day_name===day);if(ex)await sb.from('workout_plan').update({workout_name:val}).eq('id',ex.id).eq('user_id',USER.id);else await sb.from('workout_plan').insert({user_id:USER.id,day_name:day,workout_name:val})}await load();alert('Workout saved')};
$('saveMeals').onclick=async()=>{let r=await sb.from('user_profiles').update({meal_template:$('mealTemplate').value}).eq('id',S.profile.id).eq('user_id',USER.id).select().single();if(r.error)alert(r.error.message);else{S.profile=r.data;food();alert('Meals saved')}};$('remEnable').onclick=async()=>{let p=await Notification.requestPermission();$('remStatus').textContent=p==='granted'?'Notifications enabled on this device.':'Notifications blocked — enable them in your browser site settings.'};
$('remTime').onchange=()=>localStorage.setItem('remTime',$('remTime').value);
$('remOn').onchange=()=>localStorage.setItem('remOn',$('remOn').checked?'1':'0');
(function initReminders(){$('remTime').value=localStorage.getItem('remTime')||'09:00';$('remOn').checked=localStorage.getItem('remOn')==='1';$('remStatus').textContent=Notification.permission==='granted'?'Notifications enabled on this device.':'Notifications not yet enabled.';
setInterval(()=>{if(!$('remOn').checked||Notification.permission!=='granted')return;let now=new Date(),hhmm=String(now.getHours()).padStart(2,'0')+':'+String(now.getMinutes()).padStart(2,'0');if(hhmm!==$('remTime').value)return;let today=iso(now);if(localStorage.getItem('remFired')===today)return;let undone=tasks(dow(now)).filter(t=>logFor(today,t.name)?.status!=='Done');if(undone.length){new Notification('Peptide Tracker reminder',{body:`Still to log today: ${undone.map(t=>t.name).join(', ')}`});localStorage.setItem('remFired',today)}},30000)})();
function calc(){let v=+$('dVial').value,w=+$('dWater').value,d=+$('dDose').value,s=+$('dSyr').value;if(!v||!w||!d)return;let conc=v/w,ml=d/conc,u=ml*100;$('oConc').textContent=conc.toFixed(2)+' mg/mL';$('oMl').textContent=ml.toFixed(3)+' mL';$('oUnits').textContent=u.toFixed(1);$('oFit').textContent=u<=s?'Fits':'Use larger'}$('calc').onclick=calc;boot();
